version: '3.9'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"  
      USERNAME: ${WINDOWS_USERNAME}
      PASSWORD: ${WINDOWS_PASSWORD}
      RAM_SIZE: "12G"  
      CPU_CORES: "4"
      DISK_SIZE: "32G"
      DISK2_SIZE: "16G"
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"    
      - "3389:3389/tcp" 
      - "3389:3389/udp" 
    volumes:
      - /tmp/docker-data:/mnt/disco1
      - windows-data:/mnt/windows-data
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/net/tun:/dev/net/tun"
    stop_grace_period: 2m
    restart: unless-stopped  
    shm_size: "2g" 
    tty: true 
    stdin_open: true 

volumes:
  windows-data:
